package internals

import (
	zconst "github.com/Oudwins/zog/zconst"
	"golang.org/x/exp/constraints"
)

// A TestFunc that takes the data as input and returns a boolean indicating if it is valid or not
type BoolTFunc[T any] func(val T, ctx Ctx) bool

// TFunc is the function that tests hold that execute on the data for validation. They use the z.Ctx to add issues if needed
type TFunc[T any] func(val T, ctx Ctx)

// TestOption is the option for a test
type TestOption func(test TestInterface)

func TestFuncFromBool[T any](fn BoolTFunc[T], test *Test[T]) { _ = "STUB: not implemented"; return }

func TestNotFuncFromBool[T any](fn BoolTFunc[T], test *Test[T]) { _ = "STUB: not implemented"; return }

func NewTestFunc[T any](IssueCode zconst.ZogIssueCode, fn BoolTFunc[T], options ...TestOption) *Test[T] {
	_ = "STUB: not implemented"
	return nil
}

type TestInterface interface {
	GetIssueCode() zconst.ZogIssueCode
	GetIssuePath() []string
	GetParams() map[string]any
	GetIssueFmtFunc() IssueFmtFunc
	SetIssueCode(code zconst.ZogIssueCode)
	SetIssuePath(path []string)
	SetParams(params map[string]any)
	SetIssueFmtFunc(fmter IssueFmtFunc)
}

// Test is a struct that represents an individual validation. For example `z.String().Min(3)` is a test that checks if the string is at least 3 characters long.
type Test[T any] struct {
	// The issue code that will be used to create the issue if the test fails
	IssueCode zconst.ZogIssueCode
	// The path to the issue
	IssuePath []string
	// The params for the test which are passed to the issue and can be used for customizing issue messages. For example `z.String().Min(3)` will have a param with the key `min` and the value `3`.
	Params map[string]any
	// The formatter for the issue. You can use this if you want to customize the message formatter for issues generated by this specific test. Not super useful but just here for completeness.
	IssueFmtFunc IssueFmtFunc
	// The function that will be executed when evaluating the test.
	Func TFunc[T]
}

func (t *Test[T]) ZProcess(valPtr T, ctx Ctx) { _ = "STUB: not implemented"; return }

func (t *Test[T]) GetIssueCode() zconst.ZogIssueCode {
	_ = "STUB: not implemented"
	return *new(zconst.ZogIssueCode)
}

func (t *Test[T]) GetIssuePath() []string { _ = "STUB: not implemented"; return nil }

func (t *Test[T]) GetParams() map[string]any { _ = "STUB: not implemented"; return nil }

func (t *Test[T]) GetIssueFmtFunc() IssueFmtFunc {
	_ = "STUB: not implemented"
	return *new(IssueFmtFunc)
}

func (t *Test[T]) SetIssueCode(code zconst.ZogIssueCode) { _ = "STUB: not implemented"; return }

func (t *Test[T]) SetIssuePath(path []string) { _ = "STUB: not implemented"; return }

func (t *Test[T]) SetParams(params map[string]any) { _ = "STUB: not implemented"; return }

func (t *Test[T]) SetIssueFmtFunc(fmter IssueFmtFunc) { _ = "STUB: not implemented"; return }

// returns a required test to be used for processor.Required() method
func Required[T any]() Test[T] { _ = "STUB: not implemented"; return nil }

// this is not an accident. required is only a test because it makes it easier to handle error messages. But the function to check if the value is a zero value is out of the scope of this test.

type LengthCapable[K any] interface {
	~[]any | ~[]K | ~string | map[any]any | ~chan any
}

func LenMin[T LengthCapable[any]](n int) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func LenMax[T LengthCapable[any]](n int) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func Len[T LengthCapable[any]](n int) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func In[T any](values []T) (Test[*T], BoolTFunc[*T]) { _ = "STUB: not implemented"; return nil, nil }

func EQ[T comparable](n T) (Test[*T], BoolTFunc[*T]) { _ = "STUB: not implemented"; return nil, nil }

func LTE[T constraints.Ordered](n T) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func GTE[T constraints.Ordered](n T) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func LT[T constraints.Ordered](n T) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}

func GT[T constraints.Ordered](n T) (Test[*T], BoolTFunc[*T]) {
	_ = "STUB: not implemented"
	return nil, nil
}
